# Generated by Django 5.1 on 2024-08-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=None),
        ),
    ]
