# Generated by Django 5.1 on 2024-08-31 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
